name: ybike
description: ybike
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  location: ^2.5.3
  http:
  mapbox_gl: ^0.10.0
  geolocator: any
  fl_chart: any
  sqflite: any
  path_provider: any
  firebase_admob: ^0.9.3+2
  firebase_core: ^0.4.2+1
  wakelock: ^0.5.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

